name: wasupmate
description: A real-time social platform for live sports discussions
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.6.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  provider: ^6.0.5
  http: ^1.4.0
  web_socket_channel: ^3.0.3
  shared_preferences: ^2.1.1
  intl: ^0.20.2
  flutter_svg: ^2.0.5
  cached_network_image: ^3.2.3
  image_picker: ^1.1.2
  path_provider: ^2.0.15
  uuid: ^4.5.1
  timeago: ^3.4.0
  url_launcher: ^6.1.11
  # Temporarily commenting out flutter_sound due to compatibility issues
  # flutter_sound: ^9.2.13
  just_audio: ^0.10.4

  flutter_spinkit: ^5.2.0
  shimmer: ^3.0.0
  flutter_secure_storage: ^9.2.4
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
